import React, { useState } from 'react';
import {
  Mail,
  FileText,
  Download,
  Eye,
  History,
  CheckCircle2,
  XCircle,
  Clock,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { formatDate, formatCurrency } from '../components/utils/formatters';

const REPORT_TYPES = [
  { value: 'Client Summary', label: 'Client Summary' },
  { value: 'Sector Summary', label: 'Sector Summary' },
  { value: 'Full Reconciliation', label: 'Full Reconciliation' }
];

// Mock historical report data for auditing
const generateReportHistory = () => {
  const history = [];
  const reports = ['Monthly Client Summary', 'Sector Performance Report', 'Full Reconciliation Report'];
  const statuses = ['success', 'success', 'success', 'success', 'failed'];
  const users = ['admin@icp.ae', 'finance@icp.ae', 'system'];

  const now = new Date();
  for (let i = 0; i < 25; i++) {
    const date = new Date(now);
    date.setDate(date.getDate() - (i * 3));

    history.push({
      id: `hist-${i + 1}`,
      reportName: reports[i % reports.length],
      type: REPORT_TYPES[i % REPORT_TYPES.length].value,
      generatedAt: date.toISOString(),
      generatedBy: users[i % users.length],
      status: statuses[i % statuses.length],
      fileSize: `${(Math.random() * 2 + 0.5).toFixed(1)} MB`,
      recipients: ['finance@icp.ae', 'management@icp.ae'].slice(0, (i % 2) + 1),
      splitRatio: { icp: 60, dalil: 40 },
      totalRevenue: Math.round(Math.random() * 5000000 + 1000000),
      clientsIncluded: Math.floor(Math.random() * 10 + 15),
      period: date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
    });
  }
  return history;
};

export default function ReportAutomation() {
  const [reportHistory] = useState(generateReportHistory());
  const [isHistoryModalOpen, setIsHistoryModalOpen] = useState(false);
  const [selectedHistoryReport, setSelectedHistoryReport] = useState(null);

  // Pagination for history
  const [historyPage, setHistoryPage] = useState(1);
  const historyPerPage = 10;
  const totalHistoryPages = Math.ceil(reportHistory.length / historyPerPage);
  const paginatedHistory = reportHistory.slice(
    (historyPage - 1) * historyPerPage,
    historyPage * historyPerPage
  );

  const handleViewHistoryDetails = (report) => {
    setSelectedHistoryReport(report);
    setIsHistoryModalOpen(true);
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'success':
        return <CheckCircle2 className="w-4 h-4 text-emerald-500" />;
      case 'failed':
        return <XCircle className="w-4 h-4 text-red-500" />;
      default:
        return <Clock className="w-4 h-4 text-amber-500" />;
    }
  };

  const getStatusStyle = (status) => {
    switch (status) {
      case 'success':
        return 'bg-emerald-50 text-emerald-700';
      case 'failed':
        return 'bg-red-50 text-red-700';
      default:
        return 'bg-amber-50 text-amber-700';
    }
  };

  return (
    <div className="space-y-8 max-w-[1600px] mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">Report History</h1>
          <p className="text-sm text-gray-500 mt-1">
            View historical report data and audit previously generated reports.
          </p>
        </div>
      </div>

      {/* Report History Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <History className="w-5 h-5 text-gray-500" />
            <h2 className="text-lg font-semibold text-gray-900">Report History</h2>
            <span className="text-sm text-gray-500">({reportHistory.length} records)</span>
          </div>
        </div>

        <Card className="border-gray-200">
          <CardContent className="p-0">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Report</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Type</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Generated</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Generated By</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Status</th>
                  <th className="text-left py-3 px-4 font-medium text-gray-600">Size</th>
                  <th className="text-right py-3 px-4 font-medium text-gray-600">Actions</th>
                </tr>
              </thead>
              <tbody>
                {paginatedHistory.map((item) => (
                  <tr key={item.id} className="border-b border-gray-100 hover:bg-gray-50">
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-gray-400" />
                        <span className="font-medium text-gray-900">{item.reportName}</span>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-gray-600">{item.type}</td>
                    <td className="py-3 px-4 text-gray-600">
                      <div>
                        <p>{formatDate(item.generatedAt)}</p>
                        <p className="text-xs text-gray-400">
                          {new Date(item.generatedAt).toLocaleTimeString('en-US', {
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </p>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-gray-600">{item.generatedBy}</td>
                    <td className="py-3 px-4">
                      <span className={`inline-flex items-center gap-1 text-xs font-medium px-2 py-1 rounded-full ${getStatusStyle(item.status)}`}>
                        {getStatusIcon(item.status)}
                        {item.status.charAt(0).toUpperCase() + item.status.slice(1)}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-gray-600">{item.fileSize}</td>
                    <td className="py-3 px-4">
                      <div className="flex items-center justify-end gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-8 w-8 p-0"
                          onClick={() => handleViewHistoryDetails(item)}
                        >
                          <Eye className="w-4 h-4 text-gray-500" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-8 w-8 p-0"
                          disabled={item.status === 'failed'}
                        >
                          <Download className="w-4 h-4 text-gray-500" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Pagination */}
            {totalHistoryPages > 1 && (
              <div className="flex items-center justify-between px-4 py-3 border-t border-gray-200">
                <div className="text-sm text-gray-500">
                  Showing {((historyPage - 1) * historyPerPage) + 1} to {Math.min(historyPage * historyPerPage, reportHistory.length)} of {reportHistory.length} records
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setHistoryPage(prev => Math.max(prev - 1, 1))}
                    disabled={historyPage === 1}
                    className="h-8 px-3"
                  >
                    <ChevronLeft className="w-4 h-4" />
                  </Button>
                  <div className="flex items-center gap-1">
                    {Array.from({ length: totalHistoryPages }, (_, i) => i + 1).map(page => (
                      <button
                        key={page}
                        onClick={() => setHistoryPage(page)}
                        className={`w-8 h-8 text-sm rounded-lg transition-colors ${
                          historyPage === page
                            ? 'bg-gray-900 text-white'
                            : 'text-gray-600 hover:bg-gray-100'
                        }`}
                      >
                        {page}
                      </button>
                    ))}
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setHistoryPage(prev => Math.min(prev + 1, totalHistoryPages))}
                    disabled={historyPage === totalHistoryPages}
                    className="h-8 px-3"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* History Details Modal */}
      <Dialog open={isHistoryModalOpen} onOpenChange={setIsHistoryModalOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Report Details</DialogTitle>
          </DialogHeader>

          {selectedHistoryReport && (
            <div className="py-4 space-y-4">
              <div className="flex items-center gap-3 pb-4 border-b border-gray-200">
                <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
                  <FileText className="w-5 h-5 text-gray-600" />
                </div>
                <div>
                  <p className="font-semibold text-gray-900">{selectedHistoryReport.reportName}</p>
                  <p className="text-sm text-gray-500">{selectedHistoryReport.type}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="bg-gray-50 rounded-lg p-3">
                  <p className="text-xs text-gray-500 uppercase">Generated At</p>
                  <p className="text-sm font-medium text-gray-900 mt-1">
                    {formatDate(selectedHistoryReport.generatedAt)}
                  </p>
                  <p className="text-xs text-gray-500">
                    {new Date(selectedHistoryReport.generatedAt).toLocaleTimeString()}
                  </p>
                </div>
                <div className="bg-gray-50 rounded-lg p-3">
                  <p className="text-xs text-gray-500 uppercase">Generated By</p>
                  <p className="text-sm font-medium text-gray-900 mt-1">
                    {selectedHistoryReport.generatedBy}
                  </p>
                </div>
                <div className="bg-gray-50 rounded-lg p-3">
                  <p className="text-xs text-gray-500 uppercase">Report Period</p>
                  <p className="text-sm font-medium text-gray-900 mt-1">
                    {selectedHistoryReport.period}
                  </p>
                </div>
                <div className="bg-gray-50 rounded-lg p-3">
                  <p className="text-xs text-gray-500 uppercase">File Size</p>
                  <p className="text-sm font-medium text-gray-900 mt-1">
                    {selectedHistoryReport.fileSize}
                  </p>
                </div>
              </div>

              <div className="bg-gray-50 rounded-lg p-3">
                <p className="text-xs text-gray-500 uppercase mb-2">Report Snapshot</p>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Split Ratio</span>
                    <span className="font-medium">{selectedHistoryReport.splitRatio.icp}/{selectedHistoryReport.splitRatio.dalil}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Total Revenue</span>
                    <span className="font-medium">{formatCurrency(selectedHistoryReport.totalRevenue)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Clients Included</span>
                    <span className="font-medium">{selectedHistoryReport.clientsIncluded}</span>
                  </div>
                </div>
              </div>

              <div className="bg-gray-50 rounded-lg p-3">
                <p className="text-xs text-gray-500 uppercase mb-2">Recipients</p>
                <div className="flex flex-wrap gap-2">
                  {selectedHistoryReport.recipients.map((email, idx) => (
                    <span key={idx} className="inline-flex items-center gap-1 text-xs bg-white border border-gray-200 px-2 py-1 rounded-full">
                      <Mail className="w-3 h-3 text-gray-400" />
                      {email}
                    </span>
                  ))}
                </div>
              </div>

              <div className="flex items-center justify-between pt-2">
                <span className={`inline-flex items-center gap-1 text-xs font-medium px-2 py-1 rounded-full ${getStatusStyle(selectedHistoryReport.status)}`}>
                  {getStatusIcon(selectedHistoryReport.status)}
                  {selectedHistoryReport.status === 'success' ? 'Successfully Generated' : 'Generation Failed'}
                </span>
              </div>
            </div>
          )}

          <DialogFooter className="flex gap-2">
            <Button variant="outline" onClick={() => setIsHistoryModalOpen(false)}>
              Close
            </Button>
            {selectedHistoryReport?.status === 'success' && (
              <Button className="bg-gray-900 hover:bg-gray-800">
                <Download className="w-4 h-4 mr-2" />
                Download Report
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

    </div>
  );
}
